apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: fluent-bit-benchmark
  labels:
    app: log-generator
spec:
  replicas: 0  # Controlled by benchmark orchestrator
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: golang:1.21-alpine
        imagePullPolicy: Always
        workingDir: /app
        command: ["/bin/sh"]
        args: ["-c", "echo '{}' > /tmp/dummy.json && while true; do sleep 30; done"]
        args:
        - "-url=http://fluent-bit:9880"
        - "-rate=1000"
        - "-duration=60s"
        - "-workers=10"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: BENCHMARK_RATE
          value: "1000"
        - name: BENCHMARK_DURATION
          value: "60s"