apiVersion: v1
kind: Service
metadata:
  name: benchmark-server
  namespace: fluent-bit-benchmark
  labels:
    app: benchmark-server
spec:
  selector:
    app: benchmark-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 8081
    targetPort: 8081
  type: ClusterIP