apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluent-bit-benchmark
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        Health_Check  On

    [INPUT]
        Name              http
        Listen            0.0.0.0
        Port              9880
        Buffer_Max_Size   1MB
        Buffer_Chunk_Size 64KB

    [FILTER]
        Name   parser
        Match  *
        Key_Name log
        Parser json
        Reserve_Data On

    [OUTPUT]
        Name  http
        Match *
        Host  benchmark-server
        Port  8080
        URI   /logs
        Format json
        Retry_Limit 3
        
        # Connection settings
        Workers               4
        net.keepalive         on
        net.keepalive_idle_timeout 30

    [OUTPUT]
        Name  prometheus_exporter
        Match *
        Host  0.0.0.0
        Port  2021
        Add_label service fluent-bit
        Add_label env benchmark

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S