apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: fluent-bit-benchmark
  labels:
    app: fluent-bit
spec:
  selector:
    app: fluent-bit
  ports:
  - name: http-input
    port: 9880
    targetPort: 9880
  - name: http-server
    port: 2020
    targetPort: 2020
  - name: metrics
    port: 2021
    targetPort: 2021
  type: ClusterIP