apiVersion: v1
kind: Service
metadata:
  name: perses
  namespace: fluent-bit-benchmark
  labels:
    app: perses
spec:
  selector:
    app: perses
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  type: ClusterIP